version: '3.1'
services:
  postgres:
    container_name: app_db
    image: postgres:13.0
    environment:
      - DEBUG=false
      - DB_EXTENSION=plpgsql,pg_trgm
      - POSTGRES_USER=webapp
      - POSTGRES_PASSWORD=d0nt4get
      - POSTGRES_DB=app
      - POSTGRES_TEST_DB=app_test
    volumes:
      - ./create-test-db.sh:/docker-entrypoint-initdb.d/create-test-db.sh
    ports:
      - "5432:5432"
    networks:
      - net1

  web:
    container_name: webapp
    privileged: true
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://webapp:d0nt4get@postgres:5432/app
      - DATABASE_TEST_URL=postgresql://webapp:d0nt4get@postgres:5432/app_test
      - FLASK_APP=web
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - APP_SETTINGS=Development
    links:
      - postgres:postgres
    ports:
      - "8080:8080"
    volumes:
      - ".:/code"
    networks:
      - net1

networks:
  net1:
    driver: bridge