name: "mars"
fullname: "mars-id-verification"

replicaCount: 3
imagePullSecret: regcred
namespace: default

image:
  repository: docker-builds.yellitech.io/mars-identity-verification
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 8080

resources: {}

configs: 
  FLASK_APP: mars.py

secrets:
  FLASK_SECRET_KEY: this-really-needs-to-be-changed
